export const createTypes = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
    
    GET_SIGNALS: 'GET_SIGNALS',
    GET_SIGNALS_REQUEST: 'GET_SIGNALS_REQUEST',
    GET_SIGNALS_SUCCESS: 'GET_SIGNALS_SUCCESS',
    GET_SIGNALS_FAILURE: 'GET_SIGNALS_FAILURE',

    GET_CRYPTO_DATA: 'GET_CRYPTO_DATA',
    GET_CRYPTO_DATA_REQUEST: 'GET_CRYPTO_DATA_REQUEST',
    GET_CRYPTO_DATA_SUCCESS: 'GET_CRYPTO_DATA_SUCCESS',
    GET_CRYPTO_DATA_FAILURE: 'GET_CRYPTO_DATA_FAILURE',

    GET_CRYPTO_NEWS: 'GET_CRYPTO_NEWS',
    GET_CRYPTO_NEWS_REQUEST: 'GET_CRYPTO_NEWS_REQUEST',
    GET_CRYPTO_NEWS_SUCCESS: 'GET_CRYPTO_NEWS_SUCCESS',
    GET_CRYPTO_NEWS_FAILURE: 'GET_CRYPTO_NEWS_FAILURE',

    GET_CRYPTO_EVENTS: 'GET_CRYPTO_EVENTS',
    GET_CRYPTO_EVENTS_REQUEST: 'GET_CRYPTO_EVENTS_REQUEST',
    GET_CRYPTO_EVENTS_SUCCESS: 'GET_CRYPTO_EVENTS_SUCCESS',
    GET_CRYPTO_EVENTS_FAILURE: 'GET_CRYPTO_EVENTS_FAILURE',

    GET_COMMENTS: 'GET_COMMENTS',
    GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

    GET_SEARCH_SIGNAL: 'GET_SEARCH_SIGNAL',
    GET_SEARCH_SIGNAL_REQUEST: 'GET_SEARCH_SIGNAL_REQUEST',
    GET_SEARCH_SIGNAL_SUCCESS: 'GET_SEARCH_SIGNAL_SUCCESS',
    GET_SEARCH_SIGNAL_FAILURE: 'GET_SEARCH_SIGNAL_FAILURE',

    POST_SIGNALS: 'POST_SIGNALS',
    POST_SIGNALS_REQUEST: 'POST_SIGNALS_REQUEST',
    POST_SIGNALS_SUCCESS: 'POST_SIGNALS_SUCCESS',
    POST_SIGNALS_FAILURE: 'POST_SIGNALS_FAILURE',


}